config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :contacts
  #root 'home#index'
  root 'contacts#index'
  get 'home/about'
  get 'home/index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/contact.rb
class Contact < ApplicationRecord
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_many :contacts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :set_contact, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [ :index, :show ]
  before_action :correct_user, only: [ :edit, :update, :destroy ]
  # GET /contacts or /contacts.json
  def index
    @contacts = Contact.all
  end

  # GET /contacts/1 or /contacts/1.json
  def show
  end

  # GET /contacts/new
  def new
    #@contact = Contact.new
    @contact = current_user.contacts.build
  end

  # GET /contacts/1/edit
  def edit
  end

  # POST /contacts or /contacts.json
  def create
    #@contact = Contact.new(contact_params)
    @contact = current_user.contacts.build(contact_params)

    respond_to do |format|
      if @contact.save
        format.html { redirect_to contact_url(@contact), notice: "Contact was successfully created." }
        format.json { render :show, status: :created, location: @contact }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contacts/1 or /contacts/1.json
  def update
    respond_to do |format|
      if @contact.update(contact_params)
        format.html { redirect_to contact_url(@contact), notice: "Contact was successfully updated." }
        format.json { render :show, status: :ok, location: @contact }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contacts/1 or /contacts/1.json
  def destroy
    @contact.destroy

    respond_to do |format|
      format.html { redirect_to contacts_url, notice: "Contact was successfully destroyed." }
      format.json { head :no_content }
    end
  end
  
  def correct_user
    @contact = current_user.contacts.find_by(id: params[:id])
    redirect_to contacts_path, notice: "Not authorized to edit this contact" if @contact.nil?
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contact
      @contact = Contact.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def contact_params
      params.require(:contact).permit(:first_name, :last_name, :email, :phone, :address, :instagram, :user_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/contacts/_contact.html.erb
<div class="bg-dark bg-opacity-75 text-white p-2 rounded-top">
  <div class="row d-flex align-items-center">
    <div class="col">
      <strong><i class="far fa-id-card"></i> Contact: <%= contact.first_name + ' ' + contact.last_name %></strong>
    </div>
  </div>
</div>
<div id="<%= dom_id contact %>" class="bg-dark bg-opacity-10 p-2 rounded">
  <div class="row d-flex align-items-center">
    <div class="col-3 text-center">
      <i class="far fa-user" style="font-size:100px"></i>
      <h4></h4>
    </div>
    <div class="col">
      <p><%= contact.email %></p>
      <p><%= contact.phone %></p>
      <p><%= contact.address %></p>
      <p><%= contact.instagram %></p>
    </div>
  </div>
</div>

app/views/contacts/_form.html.erb
<%= form_with(model: contact) do |form| %>
  <% if contact.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(contact.errors.count, "error") %> prohibited this contact from being saved:</h2>
      <ul>
        <% contact.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="p-3 border border-secondary rounded">
    <div class="input-group">
      <%= form.text_field :first_name, placeholder:"First name", class:"form-control" %>
      <%= form.text_field :last_name, placeholder:"Last name", class:"form-control"  %>
    </div>
    <div class="input-group">
      <%= form.text_field :email, placeholder:"Email", class:"form-control" %>
      <%= form.text_field :phone, placeholder:"Phone", class:"form-control"  %>
    </div>
    <div class="input-group">
      <%= form.text_field :address, placeholder:"Address", class:"form-control" %>
      <%= form.text_field :instagram, placeholder:"Instagram", class:"form-control"  %>
    </div>
    <div class="input-group">
      <%= form.number_field :user_id, id: :contact_user_id , value: current_user.id, type: :hidden %>
    </div>

    <div class="mt-3 text-end">
      <%= form.submit class:"btn btn-success" %>
    </div>
  </div>
<% end %>

app/views/contacts/edit.html.erb
<div class="bg-dark bg-opacity-75 text-white p-2 rounded-top">
  <div class="row d-flex align-items-center">
    <div class="col">
      <strong><i class="far fa-id-card"></i> Contact: <%= @contact.first_name + ' ' + @contact.last_name %> -  UPDATE</strong>
    </div>
  </div>
</div>
<%= render "form", contact: @contact %>

<div class="mt-3 p-3">
<%= link_to contacts_path, class:"btn btn-secondary" do %>
  <i class="fas fa-clipboard-list"></i> Back to contacts list
<% end %> 

<%= link_to @contact, class:"btn btn-info" do %>
  <i class="far fa-arrow-alt-circle-left"></i> Show this contact
<% end %> 
</div>

app/views/contacts/index.html.erb
<% if user_signed_in? %>

<div class="bg-dark bg-opacity-75 text-white p-2 rounded-top">
  <div class="row d-flex align-items-center">
    <div class="col">
      <strong><i class="far fa-id-card"></i> <%= current_user.email  %> - Contacts</strong>
    </div>
    <div class="col-2 text-end">
      <%= link_to new_contact_path, class:"btn btn-outline-light" do %>
        <i class="far fa-plus-square"></i> New Contact
      <% end %>
    </div>
  </div>
</div>
<div id="contacts">
  <div class="bg-dark bg-opacity-50 text-white">
    <div class="row pt-2 ps-2 pb-2">
      <div class="col"><i class="far fa-user"></i> Name</div>
      <div class="col"><i class="far fa-envelope"></i> Email</div>
      <div class="col"><i class="fab fa-instagram"></i> Instagram</div>
      <div class="col-2"></div>
    </div>
  </div>
  <% @contacts.each do |contact| %>
    <% if contact.user == current_user %>
      <div id="<%= dom_id contact %>">
        <div class="border border-secondary">
          <div class="row  pt-2 ps-2 pb-2">
            <div class="col">
             <%= link_to contact.first_name + ' ' +  contact.last_name, contact %>
            </div>
            <div class="col">
              <%= contact.email %>
            </div>
            <div class="col">
              <%= contact.instagram %>
            </div>
            <div class="col-2 d-flex justify-content-end align-items-center">
              <%= link_to edit_contact_path(contact), class:"btn btn-primary me-1", alt:"Edit", title:"Edit" do %>
                <i class="fas fa-edit"></i>
              <% end %>
              <%= button_to contact, method: :delete, form: { data: { turbo_confirm: "Are you sure?" } }, class:"btn btn-danger me-1", alt:"Delete", title:"Delete" do %>
                <i class="far fa-times-circle"></i>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  <% end %>
</div>

<% else %>

<div class="row p-3">
  <div class="col-md-4">
    <%= image_tag "_friends.png", class:"front-pic-friends" %>
  </div>
  <div class="col d-flex justify-content-start align-items-center flex-column">
    <h1 class="bigfont-title">Welcome to Your personal contacts info page</h1>
    <hr>
        <h3 class="alert alert-danger mt-3 mb-5"><strong>You have 0 contacts!</strong></h3>
        <ul class="instructions">
            <li>To start using the personal contact information page, you need to be registered or logged in (because your personal contacts belong only to you, right?)</li>
            <li>So is very easy to register, just click on the button above in the right corner and register your name and email. Simple like that.</li>
            <li>If You already registered your user just click on the button above on the right corner and log in with your user and password. Amazing easy peasy!</li>
        </ul>
  </div>
</div>

<% end %>

app/views/contacts/new.html.erb
<div class="bg-dark bg-opacity-75 text-white p-2 rounded-top">
  <div class="row d-flex align-items-center">
    <div class="col">
      <strong><i class="far fa-id-card"></i> New contact</strong>
    </div>
  </div>
</div>
<%= render "form", contact: @contact %>

<div class="mt-3 p-3">
<%= link_to contacts_path, class:"btn btn-info" do %>
  <i class="far fa-arrow-alt-circle-left"></i> Back
<% end %> 
</div>

app/views/contacts/show.html.erb
<%= render @contact %>
<div class="d-flex justify-content-end mt-1 p-2">
  <%= link_to contacts_path, class:"btn btn-secondary me-1" do %>
    <i class="fas fa-clipboard-list"></i> Back to contacts list
  <% end %>
  <%= link_to edit_contact_path(@contact), class:"btn btn-success me-1" do %>
    <i class="far fa-arrow-alt-circle-left"></i> Edit
  <% end %>
  <%= button_to @contact, method: :delete, form: { data: { turbo_confirm: "Are you sure?" } }, class:"btn btn-danger me-1", alt:"Delete", title:"Delete" do %>
    <i class="far fa-times-circle"></i> Delete
  <% end %>
</div>

app/views/home/_footer.html.erb
<footer>
    <div class="bg-darkblue text-white p-2 text-end rounded-bottom">
        <small>Developed in RubyonRails by Brenno Matthias Pereira - © All Rights Reserved.</small>
        <a href="https://www.linkedin.com/in/brenno-pereira/" target="_blank" class="ms-2 social linkedin" title="https://www.linkedin.com/in/brenno-pereira/"><i class="fa-brands fa-linkedin-in"></i></a>
        <a href="https://github.com/brennopereiradev" target="_blank" class="ms-2 social github" title="https://github.com/brennopereiradev"><i class="fa-brands fa-github"></i></a>
        <a href="mailto:brennopereiradev@gmail.com" target="_blank" class="ms-2 social gmail" title="brennopereiradev@gmail.com"><i class="fa-solid fa-paper-plane"></i></a>
    </div>
</footer>
</div>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>

app/views/home/_header.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css" referrerpolicy="no-referrer" />
    <title>Contacts</title>
  </head>
  <body>
  <div class="container">
      <header>
        <nav class="navbar navbar-expand-lg bg-darkblue rounded-top mt-3">
          <div class="container">
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
              <ul class="navbar-nav me-auto">
                <li class="nav-item">
                  <%= image_tag "f_list.png", class:"logo" %>
                  <%= link_to "Home", home_index_path, class:"nav-link" %>
                </li>
                <li class="nav-item">
                  <i class="fa-solid fa-address-book"></i>
                  <%= link_to "Contacts", root_path, class:"nav-link" %>
                </li>
                <li class="nav-item">
                  <i class="fa-solid fa-user-ninja"></i>
                  <%= link_to "About me", home_about_path, class:"nav-link" %>
                </li>
                <% if user_signed_in? %>
              </ul>
              <ul class="navbar-nav">
                <li class="nav-item">
                  <i class="fa-solid fa-user-check"></i>
                  <%= link_to "Account", edit_user_registration_path, class:"nav-link" %>
                </li>
                <li class="nav-item">
                  <i class="fa-solid fa-person-running"></i>
                  <%= button_to "Logout", destroy_user_session_path, method: :delete, class:"nav-link-button" %>
                </li>
              </ul>
              <% else %>
              </ul>
              <div class="d-flex">
                <ul class="navbar-nav">
                  <li class="nav-item">
                  <i class="fa-solid fa-user-lock"></i>
                  <%= link_to "Login / Register", new_user_session_path, class:"nav-link" %>
                  </li>
                </ul>
              </div>
              <% end %>
            </div>
          </div>
        </nav>
      </header>

app/views/home/about.html.erb
<div class="row p-3">
  <div class="col-4">
    <div class="personal_info d-flex flex-column justify-content-center align-items-center">
      <%= image_tag "_personal_pic.png", class:"img-fluid" %>
      <h1>Brenno Matthias Pereira</h1>
      <h2>UI/UX Designer <br>
         Web Designer / Web Developer <br>
         Full Stacl Developer</h2>
    </div>
  </div>
  <div class="col">
    <p>My name is Brenno and, </p>
    <p>I am a Full Stack Developer and UI/UX Designer. I have successfully worked on several design and development project implementations for various clients during my career.</p>
    <p>I am a passionate Bachelor of Computer Science with over 10 years of experience in creating and developing brands and visual identities, creating and developing websites and art direction.</p>
    <p>I am driven by the spirit of learning, analyzing and sharing. An organized, motivated, responsible and enthusiastic person with excellent time management and attention to detail.</p>
    <p>Also, I can work on tight deadlines and in a high-pressure environment with simultaneous demands and a lot of responsibility and commitment to work in a team environment.</p>
    <p>In my process of analysis and development I am responsible for:</p>
    <ul>
      <li>Ensure that the designed design meets all users' needs, ensuring their satisfaction when interacting with the company, platforms or brands. </li>
      <li>The elaboration of user navigation maps, usability tests, creation </li>
      <li>Development and implementation of innovative and attractive solutions, application prototyping (desktop, web, mobile), user flow and processes, linking communicative interaction to Design ideas.</li>
      <li>Elaboration of the quality tests of the developed application</li>
      <li>Along with customer feedback, I optimize the platforms created, performing the documentation of all processes.</li>
      <li>Benchmarks, improvement studies, creating navigability standards aimed at optimizing performance, engagement and conversion rates for platforms like desktops applications, web applications and mobiles.
    Above all, I am always looking forward to improving hard and light skills.</li>
    </ul>
  </div>
</div>

app/views/home/index.html.erb
<div class="row p-3">
  <div class="col-md-4">
    <%= image_tag "_friends.png", class:"front-pic-friends" %>
  </div>
  <div class="col d-flex justify-content-start align-items-center flex-column">
    <h1 class="bigfont-title">Welcome to Your personal contacts info page</h1>
    <hr>
        <h5 class="mb-5">Thank You for using the personal contacts info page</h5>
        <ul class="instructions">
            <li>To start using the personal contact information page, you need to be registered or logged in (because your personal contacts belong only to you, right?)</li>
            <li>So is very easy to register, just click on the button above in the right corner and register your name and email. Simple like that.</li>
            <li>If You already registered your user just click on the button above on the right corner and log in with your user and password. Amazing easy peasy!</li>
        </ul>
  </div>
</div>

app/views/layouts/_alerts.html.erb
<% if notice %>
<div class="alert alert-success alert-dismissible fade show" role="alert">
  <i class="far fa-check-circle"></i> <%= notice %>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>
<% end %>

app/views/layouts/application.html.erb
<%= render "home/header" %>
<div class="cont-main">
<%= render 'layouts/alerts' %>
<%= yield %>
</div>
<%= render "home/footer" %>